protocol_mapping:
  anySampleType: count_lines2.sh

pipelines:
  count_lines2.sh:
    name: count_lines2
    path: count_lines2.sh  # relative to this pipeline_interface.yaml file
    looper_args: False
    arguments:
      "": file
    resources:
      default:
        file_size: "0"
        cores: "1"
        mem: "1000"
        time: "01:00:00"